import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';
import test from 'node:test';

const root = resolve(import.meta.dirname, '..');
const app = readFileSync(resolve(root, 'mobile-web/app.js'), 'utf8');
const activity = readFileSync(resolve(root, 'android/app/src/main/java/com/abdelatizarzori/sentinel/MainActivity.java'), 'utf8');
const recorder = readFileSync(resolve(root, 'android/app/src/main/java/com/abdelatizarzori/sentinel/NativeAudioRecorderPlugin.java'), 'utf8');
const tts = readFileSync(resolve(root, 'android/app/src/main/java/com/abdelatizarzori/sentinel/NativeTextToSpeechPlugin.java'), 'utf8');
const transport = readFileSync(resolve(root, 'android/app/src/main/java/com/abdelatizarzori/sentinel/NativeSentinelTransportPlugin.java'), 'utf8');

test('Sentinel uses native recording, server transcription, and spoken replies on Android', () => {
  assert.match(activity, /registerPlugin\(NativeAudioRecorderPlugin\.class\)/);
  assert.match(activity, /registerPlugin\(NativeTextToSpeechPlugin\.class\)/);
  assert.match(activity, /registerPlugin\(NativeSentinelTransportPlugin\.class\)/);
  assert.ok(activity.indexOf('registerPlugin(NativeAudioRecorderPlugin.class)') < activity.indexOf('super.onCreate(savedInstanceState)'));
  assert.match(recorder, /name = "NativeAudioRecorder"/);
  assert.match(recorder, /audio\/mp4/);
  assert.match(app, /voice\.sentinelTranscribe/);
  assert.match(app, /function toggleRecordedConversation/);
  assert.match(app, /await sendMessage\(\)/);
  assert.match(app, /voiceEnabled: true/);
  assert.match(app, /NativeTextToSpeech/);
  assert.match(app, /function isNativeAndroid/);
  assert.match(app, /مسجل Sentinel الأصلي غير جاهز/);
  assert.match(app, /function requestSentinelReply/);
  assert.match(app, /credentials: 'omit'/);
  assert.match(app, /خادم Sentinel لم يرد الآن/);
  assert.match(app, /function nativeSentinelTransport/);
  assert.match(app, /function postSentinel/);
  assert.match(transport, /NativeSentinelTransport/);
  assert.match(transport, /TRANSPORT_OPERATION_DENIED/);
  assert.match(app, /function toggleVoiceCall/);
  assert.match(app, /function runVoiceCallTurn/);
  assert.match(app, /4200/);
  assert.match(tts, /TextToSpeech/);
  assert.match(tts, /checkStatus/);
  assert.match(tts, /speechStarted/);
  assert.match(tts, /fallbackLanguage/);
  assert.match(tts, /getDefaultLanguage/);
  assert.match(app, /function verifyVoiceEngine/);
  assert.match(app, /fallbackLanguage/);
  assert.match(app, /estimatedDurationMs/);
});
