import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';
import test from 'node:test';

const root = resolve(import.meta.dirname, '..');
const html = readFileSync(resolve(root, 'mobile-web/index.html'), 'utf8');
const script = readFileSync(resolve(root, 'mobile-web/app.js'), 'utf8');

test('Sentinel presents an interactive future-museum robot with direct voice controls', () => {
  assert.match(html, /sentinel-neon-3d-robot_04ad6455\.png/);
  assert.match(html, /id="robot-stage"/);
  assert.match(html, /lip-sync/);
  assert.match(html, /museum-floor/);
  assert.match(html, /plinth/);
  assert.match(html, /curator-label/);
  assert.match(html, /gallery-breathe/);
  assert.match(html, /EXHIBIT 01/);
  assert.match(html, /id="chat-log"/);
  assert.match(html, /id="knowledge-status"/);
  assert.match(html, /id="build-marker"/);
  assert.match(html, /id="chat-input"/);
  assert.match(html, /id="chat-send"/);
  assert.match(html, /id="voice-start"/);
  assert.match(html, /id="voice-stop"/);
  assert.match(html, /sentinel-library\.js/);
  assert.doesNotMatch(html, /id="call-toggle"/);
  assert.doesNotMatch(html, /id="tts-settings"/);
  assert.doesNotMatch(html, /id="weather-location"/);
  assert.doesNotMatch(html, /id="companion-input"/);
  assert.match(html, /prefers-reduced-motion/);
  assert.match(script, /function setRobotState/);
  assert.match(script, /function beginVoiceSession/);
  assert.match(script, /function stopVoiceSession/);
  assert.match(script, /function sendChatMessage/);
  assert.match(script, /function appendChatMessage/);
  assert.match(script, /setRobotState\('listening'/);
  assert.match(script, /setRobotState\('thinking'/);
  assert.match(script, /setRobotState\('speaking'/);
});
