import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';
import test from 'node:test';

const root = resolve(import.meta.dirname, '..');
const app = readFileSync(resolve(root, 'mobile-web/app.js'), 'utf8');
const activity = readFileSync(resolve(root, 'android/app/src/main/java/com/abdelatizarzori/sentinel/MainActivity.java'), 'utf8');
const recorder = readFileSync(resolve(root, 'android/app/src/main/java/com/abdelatizarzori/sentinel/NativeAudioRecorderPlugin.java'), 'utf8');
const tts = readFileSync(resolve(root, 'android/app/src/main/java/com/abdelatizarzori/sentinel/NativeTextToSpeechPlugin.java'), 'utf8');
const generatedAudio = readFileSync(resolve(root, 'android/app/src/main/java/com/abdelatizarzori/sentinel/NativeGeneratedAudioPlugin.java'), 'utf8');
const offlineArabicVoice = readFileSync(resolve(root, 'android/app/src/main/java/com/abdelatizarzori/sentinel/NativeOfflineArabicVoicePlugin.java'), 'utf8');
const transport = readFileSync(resolve(root, 'android/app/src/main/java/com/abdelatizarzori/sentinel/NativeSentinelTransportPlugin.java'), 'utf8');

test('Sentinel uses one native Android voice loop: record, transcribe, reply, speak, then stop', () => {
  assert.match(activity, /registerPlugin\(NativeAudioRecorderPlugin\.class\)/);
  assert.match(activity, /registerPlugin\(NativeTextToSpeechPlugin\.class\)/);
  assert.match(activity, /registerPlugin\(NativeGeneratedAudioPlugin\.class\)/);
  assert.match(activity, /registerPlugin\(NativeOfflineArabicVoicePlugin\.class\)/);
  assert.match(activity, /registerPlugin\(NativeSentinelTransportPlugin\.class\)/);
  assert.ok(activity.indexOf('registerPlugin(NativeAudioRecorderPlugin.class)') < activity.indexOf('super.onCreate(savedInstanceState)'));
  assert.match(recorder, /name = "NativeAudioRecorder"/);
  assert.match(recorder, /audio\/mp4/);
  assert.match(recorder, /MediaRecorder\.AudioSource\.VOICE_RECOGNITION/);
  assert.match(recorder, /setAudioSamplingRate\(16000\)/);
  assert.match(app, /voice\.sentinelTranscribe/);
  assert.match(app, /function beginVoiceSession/);
  assert.match(app, /function runVoiceTurn/);
  assert.match(app, /function stopVoiceSession/);
  assert.match(app, /TURN_DURATION_MS/);
  assert.match(app, /turnDelayResolve/);
  assert.match(app, /speechResolve/);
  assert.match(app, /NativeGeneratedAudio/);
  assert.match(app, /function isNativeAndroid/);
  assert.match(app, /function requestReply/);
  assert.match(app, /localLibraryReply\?\.reply && localLibraryReply\.localMatch/);
  assert.match(app, /نفس النص المنسوخ/);
  assert.match(app, /سؤالك للمكتبة/);
  assert.match(app, /ما سمعتش كلام واضح/);
  assert.match(app, /const BUILD_ID = 'LISTEN-BRIDGE-20260827\.5'/);
  assert.match(app, /function createTraceId/);
  assert.match(app, /function knowledgeLabel/);
  assert.match(app, /function displayReply/);
  assert.match(app, /مكتبة Android الداخلية/);
  assert.match(app, /window\.SentinelLocalLibrary/);
  assert.match(app, /traceId/);
  assert.match(app, /function requestGeminiSpeech/);
  assert.match(app, /function trySpeakReply/);
  assert.match(app, /function speakAndroidFallback/);
  assert.match(app, /function nativeTextToSpeech/);
  assert.match(app, /function speakLocalArabic/);
  assert.match(app, /function nativeOfflineArabicVoice/);
  assert.match(app, /isSafeSentinelReply/);
  assert.match(app, /الصوت المحلي تعذر/);
  assert.match(app, /الصوت البديل كينطق نفس الرد/);
  assert.match(app, /فشل الصوت المحلي والخادمي/);
  assert.match(app, /voice\.sentinelSpeech/);
  assert.match(app, /NativeGeneratedAudio/);
  assert.match(app, /NativeTextToSpeech/);
  assert.match(app, /NativeOfflineArabicVoice/);
  assert.match(app, /SERVER_TIMEOUT/);
  assert.match(app, /Sentinel كيحضّر الصوت/);
  assert.match(app, /const TURN_DURATION_MS = 6500/);
  assert.match(app, /const NATIVE_REPLY_TIMEOUT_MS = 42_000/);
  assert.match(app, /const LOCAL_LIBRARY_DEADLINE_MS = 15_000/);
  assert.match(app, /Sentinel كيربط بالخادم وكيوجد الجواب/);
  assert.match(app, /operation === 'reply'/);
  assert.match(generatedAudio, /AudioTrack\.MODE_STATIC/);
  assert.match(generatedAudio, /AUDIO_BUFFER_WRITE_FAILED/);
  assert.match(app, /credentials: 'omit'/);
  assert.match(app, /function nativeTransport/);
  assert.match(app, /function postSentinel/);
  assert.match(transport, /NativeSentinelTransport/);
  assert.match(transport, /TRANSPORT_OPERATION_DENIED/);
  assert.match(transport, /voice\.sentinelSpeech/);
  assert.match(tts, /TextToSpeech/);
  assert.match(tts, /checkStatus/);
  assert.match(tts, /speechStarted/);
  assert.match(tts, /AudioAttributes\.USAGE_MEDIA/);
  assert.doesNotMatch(tts, /openTtsSettings/);
  assert.match(app, /function requestGeminiSpeech/);
  assert.match(app, /durationMs/);
  assert.match(generatedAudio, /AudioTrack/);
  assert.match(generatedAudio, /WRITE_BLOCKING/);
  assert.match(generatedAudio, /AUDIO_PLAYBACK_ERROR/);
  assert.match(offlineArabicVoice, /name = "NativeOfflineArabicVoice"/);
  assert.match(offlineArabicVoice, /OfflineTtsSupertonicModelConfig/);
  assert.match(offlineArabicVoice, /supertonic_ar/);
  assert.match(offlineArabicVoice, /setExtra\(Collections\.singletonMap\("lang", "ar"\)\)/);
  assert.ok(app.indexOf('await speakLocalArabic(text)') < app.indexOf('await speakReply(text, signal)'));
});
